name: 'Publish test code coverage badge'
description: 'Generate and upload test code coverage badge'
inputs:
  env:
    description: 'Environment action ran against'
    required: true
    default: 'testing'
  service-name:
    description: 'Name of the microservice'
    required: true
  coverage-report:
    description: 'Full path to test coreage output file'
    required: true
    default: '/tmp/coverage.out'
  bucket:
    description: 'Gcloud bucket to publish files'
    required: true
runs:
  using: "composite"
  steps:
    - id: coverage-publisher
      run: |
        set -x
        total=`go tool cover -func=${{ inputs.coverage-report }} | grep total | grep -Eo '[0-9]+\.[0-9]+'`
        if (( $(echo "$total <= 5x0" | bc -l) )) ; then
          COLOR=red
        elif (( $(echo "$total > 80" | bc -l) )); then
          COLOR=green
        else
          COLOR=orange
        fi
        curl "https://img.shields.io/badge/coverage-$total%25-$COLOR" > ${{ inputs.service-name }}.svg
        gsutil  -h "Cache-Control: no-cache" cp ${{ inputs.service-name }}.svg gs://${{ inputs.bucket }}/${{ inputs.service-name }}.svg
        gsutil acl ch -u AllUsers:R gs://${{ inputs.bucket }}/${{ inputs.service-name }}.svg
      shell: bash